---
- name: Install vmagent
  hosts: server
  become: yes
  tasks:
  - name: Install dependencies (HTTPS support for APT)
    apt:
      name: 
        - apt-transport-https
        - software-properties-common
        - wget
      state: present
  
  - name: Add Grafana GPG key
    apt_key:
      url: "https://packages.grafana.com/gpg.key"
      state: present
  
  - name: Add Grafana APT repository
    apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      state: present
      filename: "grafana"
  
  - name: Install Grafana
    apt:
      name: grafana
      state: latest
      update_cache: yes
  
  - name: Ensure Grafana directories exist
    file:
      path: "{{ item }}"
      state: directory
      owner: grafana
      group: grafana
    loop:
      - /etc/grafana
      - /var/lib/grafana
  
  - name: Start and enable Grafana service
    ansible.builtin.systemd_service:
      name: grafana-server
      enabled: true
      state: started
  
  - name: Wait for Grafana to start (10 sec)
    wait_for:
      port: 3000
      delay: 5
      timeout: 10
  
  - name: Add VictoriaMetrics data source via Grafana API
    ansible.builtin.uri:
      url: "http://localhost:3000/api/datasources"
      method: POST
      body_format: json
      body:
        name: "VictoriaMetrics"
        type: "prometheus"
        url: "http://localhost:8428"
        access: "proxy"
        isDefault: true
      user: "admin"
      password: "admin"
      force_basic_auth: yes
      status_code: 200
      headers:
        Content-Type: "application/json"
